#!/usr/bin/env npx tsx
/**
 * scripts/fund-devnet.ts
 * Sets up devnet wallets with SOL for local testing.
 *
 * Usage:
 *   npx tsx scripts/fund-devnet.ts          # generate fresh wallets
 *   npx tsx scripts/fund-devnet.ts --load   # load existing .wallets/*.json
 */

import { Connection, Keypair, LAMPORTS_PER_SOL, PublicKey } from "@solana/web3.js";
import {
  getOrCreateAssociatedTokenAccount,
} from "@solana/spl-token";
import bs58 from "bs58";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const RPC = process.env.SOLANA_RPC_URL ?? "https://api.devnet.solana.com";
const connection = new Connection(RPC, "confirmed");

// USDC devnet mint
const USDC_MINT_DEVNET = new PublicKey("4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU");

// ── Helpers ────────────────────────────────────────────────────────────────────

function loadOrGenerate(filePath: string, label: string): Keypair {
  if (fs.existsSync(filePath)) {
    const raw = JSON.parse(fs.readFileSync(filePath, "utf-8")) as number[];
    const kp = Keypair.fromSecretKey(Uint8Array.from(raw));
    console.log(`[fund] ${label}: loaded existing keypair ${kp.publicKey.toBase58()}`);
    return kp;
  }
  const kp = Keypair.generate();
  console.log(`[fund] ${label}: generated NEW keypair ${kp.publicKey.toBase58()}`);
  return kp;
}

async function airdropSol(keypair: Keypair, label: string, solAmount: number): Promise<void> {
  const balance = await connection.getBalance(keypair.publicKey);
  const solBalance = balance / LAMPORTS_PER_SOL;
  console.log(`[fund] ${label}: current balance = ${solBalance.toFixed(4)} SOL`);

  if (solBalance >= solAmount) {
    console.log(`[fund] ${label}: already funded, skipping airdrop`);
    return;
  }

  try {
    const sig = await connection.requestAirdrop(
      keypair.publicKey,
      solAmount * LAMPORTS_PER_SOL
    );
    await connection.confirmTransaction(sig, "confirmed");
    console.log(`[fund] ${label}: airdropped ${solAmount} SOL (tx: ${sig.slice(0, 16)}...)`);
  } catch (err) {
    console.warn(`[fund] ${label}: airdrop failed (rate limit?). Try again in 30s or use solana airdrop CLI.`);
  }
}

async function ensureUsdcAta(keypair: Keypair, label: string): Promise<string> {
  try {
    const ata = await getOrCreateAssociatedTokenAccount(
      connection,
      keypair,
      USDC_MINT_DEVNET,
      keypair.publicKey
    );
    console.log(`[fund] ${label}: USDC ATA: ${ata.address.toBase58()}`);
    return ata.address.toBase58();
  } catch (err) {
    console.warn(`[fund] ${label}: USDC ATA creation failed (need SOL first)`);
    return "<not-created>";
  }
}

// ── Main ───────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const loadExisting = process.argv.includes("--load");
  console.log(`[fund] Mode: ${loadExisting ? "load existing" : "generate new"} wallets\n`);

  const walletsDir = path.join(ROOT, ".wallets");
  fs.mkdirSync(walletsDir, { recursive: true });

  const agentPath = path.join(walletsDir, "agent.json");
  const proxyPath = path.join(walletsDir, "proxy.json");

  // Load or generate
  const agentWallet = loadExisting
    ? loadOrGenerate(agentPath, "agent")
    : Keypair.generate();
  const proxyWallet = loadExisting
    ? loadOrGenerate(proxyPath, "proxy")
    : Keypair.generate();

  if (!loadExisting) {
    console.log(`[fund] agent: generated NEW keypair ${agentWallet.publicKey.toBase58()}`);
    console.log(`[fund] proxy: generated NEW keypair ${proxyWallet.publicKey.toBase58()}`);
  }

  // Save keypair files
  fs.writeFileSync(agentPath, JSON.stringify(Array.from(agentWallet.secretKey)));
  fs.writeFileSync(proxyPath, JSON.stringify(Array.from(proxyWallet.secretKey)));
  console.log(`\n[fund] Keypair files saved to .wallets/`);

  // Airdrop SOL
  console.log("\n--- Airdrop SOL ---");
  await airdropSol(agentWallet, "agent", 2);
  await airdropSol(proxyWallet, "proxy", 2);

  // Create USDC ATAs
  console.log("\n--- USDC ATAs ---");
  const agentAta = await ensureUsdcAta(agentWallet, "agent");
  const proxyAta = await ensureUsdcAta(proxyWallet, "proxy");

  // Output base58 secret keys for .env
  const agentSecretB58 = bs58.encode(agentWallet.secretKey);
  const proxySecretB58 = bs58.encode(proxyWallet.secretKey);

  // Write .env file
  const envContent = `# Auto-generated by fund-devnet.ts — DO NOT COMMIT
SOLANA_RPC_URL=${RPC}
TEE_RPC_URL=https://tee.magicblock.app
PER_API_URL=https://per.magicblock.app
COINBASE_FACILITATOR_URL=https://x402.org/facilitator
USDC_MINT=${USDC_MINT_DEVNET.toBase58()}
PROXY_PORT=3001
DASHBOARD_URL=http://localhost:3000

# Proxy wallet (base58 secret key)
PROXY_WALLET_SECRET_KEY=${proxySecretB58}

# Agent wallet (for demo only)
AGENT_SECRET_KEY=${agentSecretB58}

# Proxy public key (for reference)
PROXY_PUBKEY=${proxyWallet.publicKey.toBase58()}
AGENT_PUBKEY=${agentWallet.publicKey.toBase58()}
AGENT_USDC_ATA=${agentAta}
PROXY_USDC_ATA=${proxyAta}
`;

  fs.writeFileSync(path.join(ROOT, ".env"), envContent);

  console.log("\n========================================");
  console.log("  Shadow Proxy — Devnet Wallets Ready");
  console.log("========================================");
  console.log(`  Proxy pubkey:  ${proxyWallet.publicKey.toBase58()}`);
  console.log(`  Agent pubkey:  ${agentWallet.publicKey.toBase58()}`);
  console.log(`  Proxy ATA:     ${proxyAta}`);
  console.log(`  Agent ATA:     ${agentAta}`);
  console.log(`\n  .env written with base58 secret keys.`);
  console.log(`  Run: cd proxy && npm run dev`);
  console.log("========================================\n");
}

main().catch(console.error);
